# Generated by Django 3.2.8 on 2021-10-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Colleage', models.CharField(max_length=20)),
                ('Branch', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=40)),
                ('Roll', models.IntegerField()),
            ],
        ),
    ]
